/* tslint:disable */
/* eslint-disable */
/**
 * Text Similarity Service
 * A service to create, update, delete, and find similar text embeddings, storing them in a local vector database.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

